---
- name: Assign the PostgreSQL package
  ansible.builtin.set_fact:
    _postgresql_package_name: "postgresql-{{ postgresql_server_version }}"
  when: postgresql_server_version is defined

- name: Ensure PostgreSQL is installed
  ansible.builtin.package:
    name: "{{ _postgresql_package_name | default('postgresql') }}"
    state: present
  register: postgresql_server_package_result

- name: Backup the original PostgreSQL configuration file  # noqa:  no-handler
  ansible.builtin.copy:
    src: "{{ postgresql_server_configuration_dir }}/postgresql.conf"
    dest: "{{ postgresql_server_configuration_dir }}/postgresql.conf.orig"
    owner: root
    group: root
    mode: '0640'
    remote_src: true
  when: postgresql_server_package_result is changed

- name: Ensure PostgreSQL is configured
  ansible.builtin.template:
    src: "etc/postgresql/{{ postgresql_server_version }}/postgresql.conf.j2"
    dest: "{{ postgresql_server_configuration_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
