---
galaxy_info:
  role_name: postgresql_client
  author: dubzland
  description: Installs the PostgreSQL client tools.
  license: MIT
  min_ansible_version: '2.14'

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal

  galaxy_tags:
    - linux
    - debian
    - ubuntu
    - database
    - postgres
    - postgresql

dependencies:
  - role: postgresql_common
