---
variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TLS_CERTDIR: "/certs"
  BASH_ENV: /root/.bashrc
  ANSIBLE_COLLECTIONS_PATH: $CI_BUILDS_DIR/ansible/collections
  GIT_CLONE_PATH: $ANSIBLE_COLLECTIONS_PATH/ansible_collections/$CI_PROJECT_NAMESPACE/postgresql
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  cache:
    key:
      prefix: lint
      files:
        - requirements-dev.txt
    paths:
      - .cache/pip/
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3-slim
  before_script:
    - pip install -r requirements-test.txt
  script:
    - ansible-lint
    - yamllint .

molecule:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdubz/ci-docker-python:${PYTHON_VERSION}
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24.0.7-dind
      alias: docker
  cache:
    key:
      files:
        - requirements-test.txt
        - tox.ini
      prefix: test-$PYTHON_VERSION
    paths:
      - .cache/pip
      - .tox/
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.9', '3.10', '3.11', '3.12']
        MOLECULE_DISTRO: ['debian:bullseye-slim', 'debian:bookworm-slim', 'ubuntu:focal', 'ubuntu:jammy']
  before_script:
    - pip install -r requirements-test.txt
  script:
    - tox

build:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3-slim
  cache:
    key:
      files:
        - requirements-dev.txt
    paths:
      - .cache/pip
  artifacts:
    paths:
      - "${CI_PROJECT_NAMESPACE}-postgresql-${CI_COMMIT_REF_NAME}.tar.gz"
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - ansible-playbook -i 'localhost,' .deploy/main.yml -e "COLLECTION_VERSION=$CI_COMMIT_REF_NAME"
  only:
    - tags

deploy:
  stage: deploy
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3-slim
  cache:
    key:
      files:
        - requirements-dev.txt
    paths:
      - .cache/pip
  dependencies:
    - build
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - ansible-galaxy collection publish --token "$GALAXY_API_TOKEN" "./${CI_PROJECT_NAMESPACE}-postgresql-${CI_COMMIT_REF_NAME}.tar.gz"
  only:
    - tags
