---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "molecule-postgresql-bookworm"
    image: "${REGISTRY_PROXY_URL}jdubz/ci-systemd:1.1-bookworm"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: "molecule-postgresql-bullseye"
    image: "${REGISTRY_PROXY_URL}jdubz/ci-systemd:1.1-bullseye"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: "molecule-postgresql-jammy"
    image: "${REGISTRY_PROXY_URL}jdubz/ci-systemd:1.1-jammy"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: "molecule-postgresql-focal"
    image: "${REGISTRY_PROXY_URL}jdubz/ci-systemd:1.1-focal"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
